language: java
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r20-linux.tgz
  - tar -zxf android-sdk_r20-linux.tgz
  # setup your ANDROID_HOME and PATH environment variables
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  9 = 2.3.3 or API level 10
  - android update sdk --filter 1,2,5 --no-ui --force
  # create AVD
  - android create avd --name default-cli --target "Google Inc.:Google APIs:15" --skin WVGA854
  # start AVD
  - emulator -avd default-cli
# Maven tweaks
install: /bin/true # install is handled by Maven itself
script: mvn clean install
