language: java
jdk: oraclejdk7
env:
  global:
    - ANDROID_SDK_TAR=android-sdk_r21.1-linux.tgz
    - ANDROID_MIN_SDK=android-8
    - ANDROID_TARGET_SDK=android-15
    - ANDROID_SDKS=38 # ARM EABI v7a System Image, Android API 15, revision 2
  matrix:
    - ANDROID_TARGET=$ANDROID_MIN_SDK      ANDROID_ABI=armeabi
    - ANDROID_TARGET=$ANDROID_TARGET_SDK   ANDROID_ABI=armeabi-v7a

before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/$ANDROID_SDK_TAR
  - tar xzf $ANDROID_SDK_TAR
  # setup your ANDROID_HOME and PATH environment variables
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}

  # List available system images with their IDs
  - android list sdk --all |grep "System Image"
  # Install required components: system image, platform and build tools etc.
  - echo y | android update sdk --filter $ANDROID_SDKS,$ANDROID_TARGET_SDK,platform-tools,build-tools-17.0.0 --all --no-ui --force
  # Install application-specific dependencies: minimum/target SDKs, extras, Google APIs etc.
  - echo yes | android update sdk --filter extra-android-support,$ANDROID_MIN_SDK --all --no-ui --force

  # create AVD
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI --sdcard 32M

  # start AVD
  - emulator -avd test -no-skin -no-audio -no-window &

script: mvn --file integration-tests/pom.xml verify -Dandroid.device=test
